### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by kentcdodds** [gnapse/jest-dom#1]
Hey! Congrats on the 1.0.0 release! :tada:

**Comment by gnapse** [comment]
Haha, yes. Thanks for the warm welcome! 🎉

BTW semantic releases are not a small thing to grasp for beginners. I got stuck first on [a couple](https://github.com/semantic-release/cli/issues/202) [of issues](https://github.com/semantic-release/cli/issues/204) with their cli.

Then I got stuck figuring out why my initial commit did not trigger a release. If you ask me, the first push should always trigger a release regardless of the commits involved. But not according to [build output](https://travis-ci.org/gnapse/jest-dom/builds/364737010#L576). Guess there must be a reason for that behavior.

Now I do not have a README in the [npm package page](https://www.npmjs.com/package/jest-dom) so if you can help with why is that happening, it'll be great.

**Comment by kentcdodds** [comment]
Yeah, I'm pretty used to semantic-release now so issues don't normally come up for me anymore.

I'm not sure what's up with the README. But try pushing a manual release (see `other/manual-releases.md`) and see what happens.
