### ISSUE TITLE
Document supported types of arguments for all matchers in the README

### ISSUE THREAD

**Issue by gnapse** [gnapse/jest-dom#33]
Following up [this comment](https://github.com/gnapse/jest-dom/pull/24#issuecomment-403614587) and the discussion above it, I think it's important that we document explicitly in the README the supported types of arguments for all custom matchers provided by this library.

**Comment by smacpherson64** [comment]
Hi @gnapse, what format would you prefer to see them in?

**Comment by gnapse** [comment]
Yup, that sounds good. I'd use "arguments" instead of "parameters" though.

Alternatively, we could also put the function signature, pretty much as they're already defined in the [`extend-expect.d.ts`](https://github.com/gnapse/jest-dom/blob/master/extend-expect.d.ts) file.

What do you think?

**Comment by smacpherson64** [comment]
👍 Arguments is better!

Something like below?
```
toHaveTextContent(text: string | RegExp)
``` 

Along that same lines, it would be good to add `jsdocs` in the types so the descriptions show up in IDEs!

**Comment by smacpherson64** [comment]
The types version is better IMO. :-)!

**Comment by gnapse** [comment]
> The types version is better IMO

Not sure which alternative you mean with this. But feel free to go ahead with what you think is best and make the change if you'd like. We can review the details in the PR.

**Comment by smacpherson64** [comment]
Sorry! I was meaning to display the types (from the extend-expect.d.ts), I plan to add this later today!
