### ISSUE TITLE
Reformat README to use generic DOM selectors

### ISSUE THREAD

**Issue by smacpherson64** [gnapse/jest-dom#50]
### Problem description:
The problem discussed in #47 was that the documentation is tightly coupled with `dom-testing-library`. End users may get confused, thinking `jest-dom` requires `dom-testing-library` selectors to work. 

### Suggested solution:
Update the README to use generic DOM selectors: `document.querySelector` in all examples.

### Option 1:
**Specific section for dom-testing-library:**
Create a section discussing how to use it with `dom-testing-library` with examples and a link.

### Option 2: 
**Each section could have examples for both:**

### Option 2: using `<details>` example

<details open>
<summary><strong>Example using document.querySelector</strong></summary>

<div class="highlight highlight-source-js">
<pre>
// <div class="some-item">test</div>
const element = document.querySelector('.some-item');
expect(element)...
// ...
</pre>
</div>
</details>

<details>
<summary><strong>Example using dom-testing-library</strong></summary>

<div class="highlight highlight-source-js">
<pre>
// <div class="some-item">test</div>
expect(queryByText('test'))...
// ...
</pre>
</div>
</details>

<hr>

### Example using document.querySelector
```javascript
// <div class="some-item">test</div>
const element = document.querySelector('.some-item');
expect(element)...
```

### Example using dom-testing-library
```javascript
// <div class="some-item">test</div>
expect(queryByText('test'))...
```

**Comment by gnapse** [comment]
Thanks for raising this issue for discussion!

On a second thought, maybe we can leave it as is, and add a brief paragraph starting the [Custom Matchers](https://github.com/gnapse/jest-dom#custom-matchers) and before each individual matcher documentation, stating something along these lines:

> Some of the examples below documenting each custom matcher make use of [`dom-testing-library`'s querying APIs](https://github.com/kentcdodds/dom-testing-library#usage). These are not part of this library, and are not required to use this library either. You can also use any built-in DOM APIs to query elements off the DOM, such as [`querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector).

This way the change is smaller, we advertise `dom-testing-library` even more (not that it needs any more advertising 😄) and we foster its use and the best practices that come with it.

What do you think?

**Comment by smacpherson64** [comment]
Hrm, Personally, I like doing both, adding the paragraph and reformatting to something like **Option 2: using direct example** above. It makes the examples consistent! I really think it looks nice when we remove the following lines on the examples. This is just my opinion, so I am open to anything! I want it to be the best we can make it.


```
// add the custom expect matchers once
import 'jest-dom/extend-expect'
// ...
// ...
```

<hr>

### `toBeEmpty`

```typescript
toBeEmpty()
```

This allows you to assert whether an element has content or not.

### Examples
```<span data-testid="not-empty"><span data-testid="empty"></span></span>```

#### Using document.querySelector
```javascript
expect(document.querySelector('[data-testid="empty"]').toBeEmpty()
expect(document.querySelector('[data-testid="not-empty"]').not.toBeEmpty()
```

#### Using dom-testing-library
```javascript
expect(queryByTestId(container, 'empty')).toBeEmpty()
expect(queryByTestId(container, 'not-empty')).not.toBeEmpty()
```

**Comment by gnapse** [comment]
Ok, sounds good. Please go for it. I won't be able to work much on this for the next week or so because I'll be traveling to the US. I'll be able to give feedback, check notifications here on GitHub, etc. Thanks!

**Comment by smacpherson64** [comment]
Hey @gnapse, I hope your trip goes well! I am planning to complete by Monday!
