### ISSUE TITLE
HtmlElementTypeError for custom jsdom instance

### ISSUE THREAD

**Issue by sheerun** [gnapse/jest-dom#58]
* `jest-dom` version: 1.11.0
* `node` version: 10.4.1
* `npm` (or `yarn`) version: yarn 1.7.0

### Relevant code or config:

```js
describe('Index', () => {
  it('Suggests cities to search by', async () => {
    const { window } = await next.render('/')
    expect(window.document).toHaveTextContent('Warszawa')
  })
})
```

next.render is a helper I've created that returns custom jsdom instance

### What you did:

Tried to use toHaveTextContent matcher with custom jsdom instance

### What happened:

Error is thrown:

```
    received value must be an HTMLElement or an SVGElement.
    Received:
      object:
```

### Reproduction:

As above

### Problem description:

It seems you throw HtmlElementTypeError with `htmlElement instanceof HTMLElement` but the element that I pass has separate of HTMLElement created along separate window object.

See:

```
const { window } = new JSDOM(...)
console.log(window.document instanceof Document) # => false
console.log(window.document instanceof window.Document) # => true
```

### Suggested solution:

- Search for Document class in scope of passed container?
- Use `constructor.name`, `__proto__.constructor.name`,` __proto__.__proto__.constructor.name` etc. instead of `instanceof`?

**Comment by sheerun** [comment]
Also, why I do it? Among others here's the quote for jsdom readme:

```
Note that we strongly advise against trying to "execute scripts" by mashing together the jsdom and Node global environments (e.g. by doing global.window = dom.window), and then executing scripts or test code inside the Node global environment. Instead, you should treat jsdom like you would a browser, and run all scripts and tests that need access to a DOM inside the jsdom environment, using window.eval or runScripts: "dangerously". This might require, for example, creating a browserify bundle to execute as a <script> element—just like you would in a browser.
```

**Comment by gnapse** [comment]
Can you provide a small repo where others can reproduce the problem? Also, even better, if you can provide the fix yourself, attempting what you suggest in the suggested solution section, that'd be great.

Thanks!

**Comment by sheerun** [comment]
Here you go...

```
npm init --force
npm install --save jsdom jest-dom
```

And execute following file:

```es6
const { JSDOM } = require('jsdom')
const { toHaveTextContent } = require('jest-dom')
const { window } = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
toHaveTextContent(window.document, 'Hello world')
```

**Comment by sheerun** [comment]
I don't want to suggest any fix, I just think it should work with this method of using

**Comment by gnapse** [comment]
Sorry for the delayed response.

I'm not familiar with using custom jsdom instances. So I do not feel comfortable fixing it myself. It seems you have some suggested solutions in your original issue report above. Maybe you can contribute a fix yourself?

**Comment by smakosh** [comment]
Having the same issue, for reproduction, use the example provided in the documentation of the testing library for react native
