### ISSUE TITLE
Should .toHaveTextContent be case-sensitive?

### ISSUE THREAD

**Issue by lourenci** [gnapse/jest-dom#71]
I don't know if this is a bug or it is a feature, but I expected that `.toHaveTextContent` was case-sensitive. I could address that if it is a bug.

* `jest-dom` version: 2.1.1

### What you did:

```html
<div className="App">
  <h1>Hello CodeSandbox</h1>
  <h2>Start editing to see some magic happen!</h2>
</div>
```
I expect the expect below would fail, but it passes.
```js
expect(subject.container.querySelector("h1")).toHaveTextContent("hello codesandbox");
```

**Comment by kentcdodds** [comment]
I agree, it should be case sensitive. If people want case insensitivity they should use a regex.
