### ISSUE TITLE
Better document toHaveTextContent's case sensitiveness

### ISSUE THREAD

**Issue by gnapse** [gnapse/jest-dom#73]
After having merged #72 I've realized the README is not clear about this, not even the examples hint at this, and they were even inadequate for how it behaved before this change.

`toHaveTextContent` documentation should be explicit about this. Maybe even mentioning that if someone wants it to behave as case-insensitive, they should use a regex with the `i` modifier (`/some text/i`) instead of a string.

@lourenci can you take this? I could but maybe you can tackle it before I can.

**Comment by lourenci** [comment]
@gnapse yes, I can.
