### ISSUE TITLE
New toBeEnabled() matcher

### ISSUE THREAD

**Issue by lourenci** [gnapse/jest-dom#76]
### Describe the feature you'd like:

I'd like a matcher to check if a specific input element is enabled.

### Describe alternatives you've considered:

Today, I check for the input being enable using the `not.toBeDisabled()` matcher. I think It would be better for the read/clarity of the test, I be able to write `.toBeEnabled()`.

**Comment by gnapse** [comment]
Hmm, I get your point. We did it as `.toBeDisabled` because more often than not, being disabled is the exception. But yes, it makes sense to have them both. Do you want to [contribute it](http://makeapullrequest.com) to this library?

**Comment by alexkrolick** [comment]
fwiw `disabled` is a DOM attribute and enabled is not really

**Comment by gnapse** [comment]
Yes, that's why we went with `toBeDisabled`. But OTOH, I also dislike double negations. I really do not have a strong opinion against it, that's why I think it's ok. But I'm also not super convinced it's needed.

**Comment by lourenci** [comment]
@gnapse I can address that. :)
