### ISSUE TITLE
New toBeEmpty custom matcher

### ISSUE THREAD

**Issue by gnapse** [gnapse/jest-dom#8]
As discussed in #4, this library needs some sort of `.toBeEmpty` custom matcher. This will pass if the given element does not contain any child elements.

```javascript
expect(element).toBeEmpty()
```

A few aspects of this are open to discussion. We'd like to come up with a different name that would be clearer and avoid name clashes with other matchers out there that might be checking emptiness of other things (e.g. array or collections of some sort).

### How?

// TODO

### Why?

Presumably doing the equivalent checks on one's own is not straightforward and concise enough.

**Comment by smacpherson64** [comment]
@gnapse with empty does this mean text nodes as well as element nodes?

**Comment by kentcdodds** [comment]
As a user I would expect empty to mean that `element.innerHTML === ''`

**Comment by smacpherson64** [comment]
Sounds good!
