### ISSUE TITLE
.toBeVisible should consider "hidden" attribute

### ISSUE THREAD

**Issue by diegohaz** [gnapse/jest-dom#84]
### Describe the feature you'd like:

`expect(element).toBeVisible()` should return `false` if `element.hasAttribute('hidden')` unless it's been explicitly shown with styles (`display && display !== 'none'` for example).

### Suggested implementation:

Add `&& !element.hasAttribute('hidden')` here, plus a check on `display`:
https://github.com/gnapse/jest-dom/blob/238cc91bfaffa9dd5baed1b5a02d060909f7c30c/src/to-be-visible.js#L17-L22

### Describe alternatives you've considered:

I'm using `.toHaveAttribute("hidden")`, but I feel like I'm testing an implementation detail.

**Comment by diegohaz** [comment]
I think it may be considered a bug since the element is not visible on the browser.

**Comment by gnapse** [comment]
Thanks for the bug report @diegohaz. Do you want to contribute this yourself? If not I can tackle it later this week.

**Comment by diegohaz** [comment]
Sure, I'm gonna do that later today.
