### ISSUE TITLE
Codesandbox expect is not defined

### ISSUE THREAD

**Issue by viniciusavieira** [gnapse/jest-dom#88]
* `jest-dom` version: 3.1.3
* `react-testing-library` version: 6.0.0

### Relevant code or config:

https://codesandbox.io/s/ymjjk77x0z

### What you did:

There are 2 files in the __tests__ folder, one imports jest-dom and another does not.

```ErrorFormatDateView.test.js``` Does import jest-dom and breaks by not finding the expect export.

```FormatDateView.test.js``` Does not import, and using other matches can pass the test case.

### Suggested solution:

```jest-dom/extend-expect``` should export a default expect from jest.

**Comment by kentcdodds** [comment]
This is a codesandbox bug

**Comment by kentcdodds** [comment]
Cc @compuives, of all the things that codesandbox could do, this is the number one thing I would like: fix the testing story so this works like it used to.

**Comment by CompuIves** [comment]
I'll make sure to put the fix in the update tomorrow!

**Comment by viniciusavieira** [comment]
I've tested it today and seems to be working fine.
![image](https://user-images.githubusercontent.com/2073019/54636961-4a966280-4a66-11e9-8ac4-8e859c958379.png)

Thanks for the effort guys.

**Comment by gnapse** [comment]
Wow that was fast! Thanks @CompuIves!

**Comment by SheaBelsky** [comment]
Wanted to bring this issue back up, as there's another issue having similar problems in running unit tests from CodeSandbox:

https://github.com/codesandbox/codesandbox-client/issues/2311

**Comment by CompuIves** [comment]
Fix is underway!

**Comment by weyert** [comment]
Top dank je wel!
