### ISSUE TITLE
toHaveTextContent should ignore whitespace

### ISSUE THREAD

**Issue by gnapse** [gnapse/jest-dom#9]
* `jest-dom` version: 1.0.0

#### What you did:

```javascript
//  <span>
//    Step
//      1
//    of 4
//  </span>

expect(container.querySelector('span')).toHaveTextContent('Step 1 of 4')
```

#### What happened:

```
    expect(element).toHaveTextContent()

    Expected element to have text content:
      Step 1 of 4
    Received:

          Step
            1
          of 4
```

#### Problem description:

This was initially reported in kentcdodds/react-testing-library#53, and it was really about a bug in kentcdodds/dom-testing-library#19. However, this also applies to a piece of code in jest-dom. The custom matchet `.toHaveTextContent` should also ignore a node's whitespace in its text content before determining if the text matches the expectation.

#### Suggested solution:

Normalize the text of a node before using to match it with the expected text. Similar to what was done in kentcdodds/dom-testing-library#19

**Comment by kentcdodds** [comment]
Actually, `dom-testing-library` actually exposes its `matches` function, we should probably use that too :+1:

**Comment by gnapse** [comment]
That fix was not done in `matches` because that one is used in other contexts. But perhaps we wanted all other contexts to be affected too? In that case we need to revisit my fix to be done in that way instead.

**Comment by kentcdodds** [comment]
No, I was just suggesting while you're working on this you could do that as well. Perhaps we should also expose the `getText` method from `dom-testing-library` as well 🤔

**Comment by gnapse** [comment]
@kentcdodds wouldn't there be a problem if two packages depend on each other?

**Comment by smacpherson64** [comment]
Hrm, @kentcdodds and @gnapse, would `element.innerText` work? It normalizes text and removes whitespace. The downside is it does not replace tabs with spaces, however we could write a small wrapper for that!

**Comment by smacpherson64** [comment]
Hrm a few more possible gotchas:

While textContent gets the content of all elements, including <script> and <style> elements, innerText does not, only showing “human-readable” elements.

innerText is aware of styling and won’t return the text of “hidden” elements, whereas textContent does.

From: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by smacpherson64** [comment]
-- Removed idea about using `element.innerText`.

**Comment by smacpherson64** [comment]
From @noinkling:
https://github.com/gnapse/jest-dom/pull/56#issuecomment-426535211

This change breaks testing for text within child elements (nested text), because you switched to using `getNodeText` from dom-testing-library, which only considers immediate text node children.

Example:

```html
<div class="error">
  <ul>
    <li>Email format is invalid</li>
  </ul>
</div>
```

I just want to write something like `expect(errorBox).toHaveTextContent('email format')`, instead of tightly coupling my tests to whatever the internal structure may be. This worked fine in the previous version because it used `.textContent` (which is what I would expect a method named "toHaveTextContent" to use).

Since it now fails, the best I can come up with is something like `expect(errorBox.textContent).toMatch(/email format/i)`, which isn't nearly as nice.

**Comment by smacpherson64** [comment]
From @kentcdodds:
https://github.com/gnapse/jest-dom/pull/56#issuecomment-426630987

`expect(errorBox).toHaveTextContent('email format')`

I don't think that would have worked before. The regex is how I would have done that before and now 🤔

**Comment by smacpherson64** [comment]
Hrm, [Line 5: of get-node-text](https://github.com/kentcdodds/dom-testing-library/blob/master/src/get-node-text.js#L5) filters out all non TextNodes. So it would only get one level deep. If we switch the `&&` to `||` I think it would get all sub text as well:

Example:
https://codesandbox.io/s/5xl195pynx
The console.log shows the examples

**Comment by smacpherson64** [comment]
The normalization was moved to: https://github.com/kentcdodds/dom-testing-library/blob/863741a204bca67c63ca3944770727e5afb071d2/src/matches.js#L39-L46

**Comment by noinkling** [comment]
Why not just normalize the result of `.textContent`?

**Comment by smacpherson64** [comment]
That's a really good point haha!

**Comment by malixsys** [comment]
As @smacpherson64 predicted, this broke a lot of our tests... Is that allowed under SemVer?
```
            expect(signInSection).toHaveTextContent(
                '[DICT] Welcome,Kermit the Frog'
            );
```

**Comment by gnapse** [comment]
@malixsys I'm so sorry.

I'm not sure how you're specifying jest-dom's version number, but this was indeed published as a breaking change, and it's the breaking change that switched jest-dom from v1.x to v2. I think that would not violate SemVer terms.

Maybe I'm missing something. Can you clarify what version you're using that broke your tests, and under which version they used to work? Your code snippet above does not give much information.

**Comment by malixsys** [comment]
@gnapse Ah yes, indeed! Sorry, thought this was in 2.0.1! No worries, 2.x has been put in the code debt column for now... :)
