### ISSUE TITLE
Invitation to move to testing-library org

### ISSUE THREAD

**Issue by kentcdodds** [gnapse/jest-dom#95]
It's up to you, but if you'd like, you're welcome to transfer this repository to the testing-library organization on GitHub. This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by gnapse** [comment]
Oops, it looks we crossed each other :) #96 

I'll close #96, can you answer me here or there if there's something to keep in mind here?

**Comment by kentcdodds** [comment]
You were so fast!

**Comment by kentcdodds** [comment]
Everything should redirect. But I recommend updating URLs as you see them :)

**Comment by gnapse** [comment]
@kentcdodds done!
